version: "3.9"

services:
  ocr-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr-fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Permet le rechargement des fichiers sans rebuild
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped