version: "3.9"

services:
  ocr-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr-fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app             # Synchronise tous les fichiers du projet pour développement
      - /app/__pycache__   # Évite les fichiers temporaires si besoin
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Paris    # (optionnel) définit le fuseau horaire
    restart: unless-stopped